services:
  users_s3:
    url: https://opa-s3-test2-auth.s3.amazonaws.com
    credentials:
      s3_signing:
        environment_credentials: {}

# ensure you configure env vars
# AWS_ACCESS_KEY_ID=$(aws configure get aws_access_key_id)
# AWS_SECRET_ACCESS_KEY=$(aws configure get aws_secret_access_key)

bundles:
  authz:
    service: users_s3
    resource: authz.tar.gz